from typing import Protocol, Any, Optional, runtime_checkable


@runtime_checkable
class ICache(Protocol):
    def get(self, key: str) -> Optional[Any]: ...
    def set(self, key: str, value: Any, ttl: Optional[int] = None) -> None: ...
    def delete(self, key: str) -> bool: ...
    def clear(self) -> None: ...
    def exists(self, key: str) -> bool: ...
