from typing import Protocol, List, Any, runtime_checkable
from ..types import VectorType


@runtime_checkable
class IEmbeddingModel(Protocol):
    @property
    def dimension(self) -> int: ...
    @property
    def model_name(self) -> str: ...
    def encode(self, input_data: Any) -> VectorType: ...
    def encode_batch(self, inputs: List[Any], batch_size: int = 32) -> List[VectorType]: ...
