from typing import Protocol, Dict, Any, Callable, runtime_checkable


@runtime_checkable
class IEventPublisher(Protocol):
    def publish(self, event_type: str, data: Dict[str, Any]) -> None: ...
    def subscribe(self, event_type: str, handler: Callable) -> None: ...
    def unsubscribe(self, event_type: str, handler: Callable) -> None: ...
