from typing import Protocol, Generic, List, Dict, Any, Optional, runtime_checkable
from ..types import T


@runtime_checkable
class IRepository(Protocol, Generic[T]):
    def add(self, entity: T) -> T: ...
    def get_by_id(self, id: Any) -> Optional[T]: ...
    def update(self, entity: T) -> T: ...
    def delete(self, id: Any) -> bool: ...
    def find(self, criteria: Dict[str, Any]) -> List[T]: ...
    def count(self) -> int: ...
