from typing import Protocol, List, Any, Optional, runtime_checkable
from ..models import SearchQuery, SearchResultItem


@runtime_checkable
class ISearchService(Protocol):
    def search(self, query: SearchQuery) -> List[SearchResultItem]: ...
    def search_text(self, query_text: str, **kwargs: Any) -> List[SearchResultItem]: ...
    def search_image(self, image_path: str, **kwargs: Any) -> List[SearchResultItem]: ...
    def search_hybrid(self, query_text: Optional[str] = None, image_path: Optional[str] = None, **kwargs: Any) -> List[SearchResultItem]: ...
