from typing import Protocol, List, Dict, Any, Optional, runtime_checkable
from ..types import VectorType
from ..models import SearchResultItem


@runtime_checkable
class IVectorDatabase(Protocol):
    def add_vectors(self, vectors: VectorType, metadata: List[Dict[str, Any]], ids: Optional[List[str]] = None) -> None: ...
    def search(self, query_vector: VectorType, k: int = 10, filters: Optional[Dict[str, Any]] = None) -> List[SearchResultItem]: ...
    def delete_vector(self, vector_id: str) -> None: ...
    def get_stats(self) -> Dict[str, Any]: ...
    def rebuild_index(self) -> None: ...
